mode: "dev"
port: 8000
start_time: "2023-01-01"
machine_id: 1

log:
  level: "debug"
  filename: "./log/bluebell.log"
  show_line: true
  prefix: "bluebell"

mysql:
  host: mysql8019
  port: 3306
  user: root
  password: root1234
  db: bluebell
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: redis507
  port: 6379
  db: 0

auth:
  exp: 24 # 7hour
  secret: "my name is ..."